# Generated by Django 4.1.4 on 2022-12-28 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media/categories/%y/%m/%d/')),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='media/meals/%y/%m/%d/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preparation_time', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('upload_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
