# Generated by Django 4.1.4 on 2022-12-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=14)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('no_of_persons', models.IntegerField()),
            ],
        ),
    ]
